### ISSUE TITLE
AttributeError: 'module' object has no attribute 'rnn_cell'

### ISSUE THREAD

**Issue by monsieurzhang** [thumt/THUMT#15]
Hi,

When I try "python $THUFOLDER/thumt/bin/trainer.py -h"
it reports like:

Traceback (most recent call last):
  File "/training/Users/THUMT/THUMT/thumt/bin/trainer.py", line 17, in <module>
    import thumt.models as models
  File "/training/Users/THUMT/THUMT/thumt/models/__init__.py", line 4, in <module>
    import thumt.models.seq2seq
  File "/training/Users/THUMT/THUMT/thumt/models/seq2seq.py", line 11, in <module>
    import thumt.layers as layers
  File "/training/Users/THUMT/THUMT/thumt/layers/__init__.py", line 6, in <module>
    import thumt.layers.rnn_cell
  File "/training/Users/THUMT/THUMT/thumt/layers/rnn_cell.py", line 13, in <module>
    class LegacyGRUCell(tf.nn.rnn_cell.RNNCell):
AttributeError: 'module' object has no attribute 'rnn_cell'

Do you have any idea to fix it?
Thanks.

**Comment by monsieurzhang** [comment]
It works now when I update TensorFlow to 1.4.0.
Thanks.
